import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import localFont from "next/font/local";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google'
import { Toaster } from "react-hot-toast";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const inter = Inter({
  subsets: ["latin"]
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="719850369388-u4vd0dd8lb8ttaltfh2f5modk9695psu.apps.googleusercontent.com">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className={inter.className}>

            <Toaster />
            {children}

          </div>
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
